# Generated by Django 3.0.5 on 2020-10-24 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201024_2234'),
        ('api', '0002_auto_20201024_1143'),
    ]

    operations = [
    ]
