# Generated by Django 3.0.5 on 2020-10-24 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_and_auth', '0002_auto_20201024_1143'),
        ('users_and_auth', '0002_auto_20201023_1502'),
    ]

    operations = [
    ]
